### ISSUE TITLE
Consolidate some nav items 

### ISSUE THREAD

**Issue by mfridman** [goconca/goconca.github.io#2]
The nav bar items are getting a bit stretchy.

Maybe we should consolidate some of the links?
- About could be (location, organizers and contact)
- Subscribe for updates could be “Subscribe”

**Comment by Gonzih** [comment]
Contact needs to be a separate anchor since I will be using it in our emailing campaigns, rest I can combine no issues.

**Comment by Gonzih** [comment]
Ok I changed mailing form to just "Subscribe", need to think how to restructure location since its not relevant atm.

**Comment by Gonzih** [comment]
Huh just "Subscribe" looks like we are just a desperate youtube channel ;). Will think about it. Dont want to merge organizers section in to about also since its not a relevant information.

**Comment by mfridman** [comment]
> Contact needs to be a separate anchor since I will be using it in our emailing campaigns, rest I can combine no issues.

Sounds good, was jotting down ideas in a GH issue.

I imagine the items will change anyways as time goes on, e.g., close cfp (remove), add section for speakers, etc.

**Comment by Gonzih** [comment]
I added a separate configuration for navigation to clean it up, now its a bit better.
