### ISSUE TITLE
Anchor tags land past their target (due to fixed navbar?)

### ISSUE THREAD

**Issue by mfridman** [goconca/goconca.github.io#5]
E.g., clicking on this link .. 

<img width="252" alt="screen shot 2019-01-19 at 12 18 09 am" src="https://user-images.githubusercontent.com/6278244/51422641-fb27d900-1b7f-11e9-9dd2-ff43edcd4fc2.png">

brings you to the correct section but obscures some of the text and anchor tag title.

<img width="709" alt="screen shot 2019-01-19 at 12 20 19 am" src="https://user-images.githubusercontent.com/6278244/51422650-2e6a6800-1b80-11e9-94e5-2893119a6770.png">

would expect something like this, where the thing you clicked on is the title and the fixed bar is no obscuring it.

<img width="368" alt="screen shot 2019-01-19 at 12 20 29 am" src="https://user-images.githubusercontent.com/6278244/51422649-2e6a6800-1b80-11e9-8b8b-2fd8eac9436c.png">

**Comment by Gonzih** [comment]
Fixed.
